ComandaDigital/Controllers/AcessoController.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using ComandaDigital.Servicos;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;

namespace ComandaDigital.Controllers
{
    public class AcessoController : Controller
    {
        private readonly ICadastroUsuarioServico cadastroUsuarioServico;

        public AcessoController(ICadastroUsuarioServico cadastroUsuarioServico)
        {
            this.cadastroUsuarioServico = cadastroUsuarioServico;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Autenticar(string email, string senha)
        {
            try
            {
                var usuario = cadastroUsuarioServico.BuscaUsuarioPorEmailSenha(email, senha);
                if (usuario == null)
                {
                    TempData["falhaAutenticacao"] = string.Format("Usuário ou senha incorreto!");
                    return View("Index");
                }

                var claims = new List<Claim> {
                    new Claim(ClaimTypes.Role, usuario.TipoUsuario.ToString()),
                    new Claim(ClaimTypes.Name, usuario.Nome),
                    new Claim("IdUsuario", usuario.Id.ToString()),
                };

                var userIdentity = new ClaimsIdentity(claims, "login");
                ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);
                await HttpContext.SignInAsync(principal);

                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml", ex);
            }
        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync();

            return RedirectToAction("Index");
        }
    }
}

ComandaDigital/Controllers/ContasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ComandaDigital.Controllers
{
    [Route("Contas/[controller]")]
    public class ContasController : Controller
    {
        [Route("[action]")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

ComandaDigital/Controllers/SalaoController.cs
using System;
using ComandaDigital.Dtos;
using ComandaDigital.Servicos;
using Microsoft.AspNetCore.Mvc;

namespace ComandaDigital.Controllers
{
    [Route("Salao/[controller]")]
    public class SalaoController : Controller
    {
        private readonly ICadastroMesaServico cadastroMesaServico;
        private readonly IPedidoServico pedidoServico;
        private readonly ISalaoService salaoService;

        public SalaoController(ICadastroMesaServico cadastroMesaServico, ISalaoService salaoService, IPedidoServico pedidoServico)
        {
            this.cadastroMesaServico = cadastroMesaServico;
            this.salaoService = salaoService;
            this.pedidoServico = pedidoServico;
        }

        [Route("[action]")]
        public IActionResult Index()
        {
            var mesas = cadastroMesaServico.ListarTodasMesas();

            return View(mesas);
        }

        [Route("[action]")]
        public IActionResult IndexItem()
        {
            try
            {
                var itens = pedidoServico.ListaTodosItemPedido();
                return View(itens);
                //var itens = pedidoServico.BuscarItemPorId(pedidoId).ItensPediddos;
                //return View(new ItemPedidoListDto { ItensPedidos = itens, PedidoId = pedidoId });
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml", ex);
            }
        }

        [Route("[action]")]
        public IActionResult Alocar(int mesaId)
        {
            var mesa = cadastroMesaServico.BuscaMesaPorId(mesaId);

            return View(mesa);
        }

        [Route("[action]")]
        public IActionResult SalvaAlocacao(int mesaId, int garcomId, string clienteNome, string clienteDocumento)
        {
            salaoService.AlocarCliente(mesaId, garcomId, clienteNome, clienteDocumento);

            return RedirectToAction("Index");
        }    
    }
}

ComandaDigital/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using ComandaDigital.Helpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Comanda Digital</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-solar.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <script src="~/js/mascaras.js"></script>
    <script src="~/js/validacao.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Comanda Digital</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Salao" asp-action="Index">Salão</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Cozinha<b class="caret"></b></a>
                            <div class="dropdown-menu" aria-labelledby="themes">
                                <a class="dropdown-item" asp-area="" asp-controller="Cozinha" asp-action="PedidoAberto">Pedidos em aberto</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Cozinha" asp-action="PedidoAndamento">Pedidos em andamento</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Cozinha" asp-action="PedidoConcluido">Pedidos em finalizados</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Pedidos" asp-action="Index">Pedidos</a>
                        </li>
                        @if (UsuarioConectadoHelper.GetTipo((User.Identity as ClaimsIdentity)) == "Gerente")
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Cadastros<b class="caret"></b></a>
                                <div class="dropdown-menu" aria-labelledby="themes">
                                    <a class="dropdown-item" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                                    @if (UsuarioConectadoHelper.GetTipo((User.Identity as ClaimsIdentity)) == "Gerente")
                                    {
                                        <a class="dropdown-item" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuários</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Mesas" asp-action="Index">Mesas</a>
                                    }
                                </div>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Contas" asp-action="Index">Fechar conta</a>
                        </li>
                        @if (UsuarioConectadoHelper.GetTipo((User.Identity as ClaimsIdentity)) == "Gerente")
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Estabelecimentos" asp-action="Index">Estabelecimento</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Acesso" asp-action="LogOut">Sair do Sistema</a>
                        </li>
                    </ul>
                </div>
                @UsuarioConectadoHelper.GetNome((User.Identity as ClaimsIdentity))
                @UsuarioConectadoHelper.GetTipo((User.Identity as ClaimsIdentity))
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer navbar-dark bg-dark text-muted">
        <div class="container">
            &copy; 2019 - ComandaDigital
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
    <div class="wrapper">
        <div class="container-fluid">
            @RenderBody()
            <div id="modalValidation" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title mt-0" id="myModalLabel">Preenchimento Incorreto</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        </div>
                        <div class="modal-body">
                            <h4>Verifique os seguintes campos</h4>
                            <span id="mensagensDeFalha"></span>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary waves-effect" data-dismiss="modal"><i class="fa fa-check-circle-o"></i> OK</button>
                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->

            <div id="modal-content-dinamic" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                @*conteudo modal dinamico*@
            </div><!-- /.modal -->


        </div> <!-- end container -->
    </div>
</body>
</html>